### ISSUE TITLE
corrections orthographiques.

### ISSUE THREAD

**Issue by EstyaV** [PartiPirate/bulletinunique.org#3]
bonsoir,
je me permets de proposer ces corrections :

> Avec la mise en place d’un bulletin unique, la gestion du bureau de vote est simplifiée:

il manque un espace devant le signe double.

> Chaque députés et chaque sénateur 

suppression du pluriel de _députés_.

> La député O'Petit à posé

le a sans accent du verbe avoir.

> Notre proposition de loi est reprise et déposé

accord de _déposée_.

> Amendement No 77

anglicisme, à discuter, normalement sous la forme n°

> Liste outils que vous pouvez utiliser pour faire la promotion du rapport autour de vous. Si vous avez créé des ressources dans cet objectif, vous pouvez nous contacter pour qu'ils soient ajoutés sur cette page (bannières, vidéos, tracts...)

il manque un article devant outils, accord de _qu'elles_ et _ajoutées_ avec _ressources_, manque un point à la phrase.

Sur le sens je rajoute : 

> L'État, ou ses représentants, les préfectures, seront responsables de la mise en page des bulletins évitant ainsi la problématique de bulletins refusés, réimprimés, dispendieux avec une logistique coûteuse.

Trop de virgules, manque sans doute quelque chose avec dispendieux. Je propose : 
L'État ou ses représentants, les préfectures, seront responsables de la mise en page des bulletins. Cela évite les problématiques de bulletins refusés ou réimprimés, surcoût logistique particulièrement dispendieux.

**Comment by Farocs** [comment]
Correction prise en compte : 
https://github.com/PartiPirate/bulletinunique.org/commit/4f698b0183c81a5013b3853b2ca6968ee8ea9e6d
